// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "GET /todo successfully",
    id: "d00dadc5-a8b0-4efe-9f41-d503f8078d23",
    method: "GET",
    address: "http://localhost:8080/todo",
    headers: {
      "X-Requested-With": "XMLHttpRequest",
      "X-Up-Fail-Target": 'form[name="delete-1"]',
      "X-Up-Target": ".container"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "POST /todo/new ",
    id: "81586e56-12fb-4634-9b13-1d4a25ada36a",
    method: "POST",
    address: "http://localhost:8080/todo/new",
    data:
      '------WebKitFormBoundaryOBJscliLYB7fwWB9\r\nContent-Disposition: form-data; name="title"\r\n\r\n1\r\n------WebKitFormBoundaryOBJscliLYB7fwWB9\r\nContent-Disposition: form-data; name="priority"\r\n\r\n1\r\n------WebKitFormBoundaryOBJscliLYB7fwWB9--\r\n',
    headers: {
      "X-Requested-With": "XMLHttpRequest",
      "X-Up-Fail-Target": 'form[name="todoForm"]',
      "X-Up-Target": ".container",
      "Content-Type":
        "multipart/form-data; boundary=----WebKitFormBoundaryOBJscliLYB7fwWB9"
    },
    post(response) {
      pm.test("Status code is 301", function() {
        pm.response.to.have.status(301);
      });
    }
  });

  postman[Request]({
    name: "GET /todo successfully",
    id: "3218e067-2599-42bf-89c0-0685eac29ef9",
    method: "GET",
    address: "http://localhost:8080/todo",
    headers: {
      "X-Requested-With": "XMLHttpRequest",
      "X-Up-Fail-Target": 'form[name="todoForm"]',
      "X-Up-Target": ".container"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "GET /todo/1/edit successfully",
    id: "a2620dc7-5243-4009-9cbd-da5de97918d0",
    method: "GET",
    address: "http://localhost:8080/todo/1/edit",
    headers: {
      "X-Requested-With": "XMLHttpRequest",
      "X-Up-Fail-Target": "body",
      "X-Up-Target": ".modalenabled"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "POST /todo/1/edit ",
    id: "6fb475a2-ea0c-4d0c-895a-b446f3087434",
    method: "POST",
    address: "http://localhost:8080/todo/1/edit",
    data:
      '------WebKitFormBoundaryoA86bG2oEI7ZFH72\r\nContent-Disposition: form-data; name="title"\r\n\r\n1\r\n------WebKitFormBoundaryoA86bG2oEI7ZFH72\r\nContent-Disposition: form-data; name="priority"\r\n\r\n1\r\n------WebKitFormBoundaryoA86bG2oEI7ZFH72\r\nContent-Disposition: form-data; name="completed"\r\n\r\non\r\n------WebKitFormBoundaryoA86bG2oEI7ZFH72--\r\n',
    headers: {
      "X-Requested-With": "XMLHttpRequest",
      "X-Up-Fail-Target": 'form[name="todoForm"]',
      "X-Up-Target": ".container",
      "Content-Type":
        "multipart/form-data; boundary=----WebKitFormBoundaryoA86bG2oEI7ZFH72"
    },
    post(response) {
      pm.test("Status code is 301", function() {
        pm.response.to.have.status(301);
      });
    }
  });

  postman[Request]({
    name: "GET /todo successfully",
    id: "a14c1097-1be8-4e45-8c04-135d224d4cc6",
    method: "GET",
    address: "http://localhost:8080/todo",
    headers: {
      "X-Requested-With": "XMLHttpRequest",
      "X-Up-Fail-Target": 'form[name="todoForm"]',
      "X-Up-Target": ".container"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });
}
